test: add colors and improve errors

diff --git a/test b/test
--- a/test
+++ b/test
@@ -4,6 +4,7 @@ norm() {
 	fd '^(libft.h|ft_[^\.]+\.c)$' -X norminette
 }
 
+color_blue="\033[0;34m"
 color_red="\033[0;31m"
 color_reset="\033[0m"
 
@@ -16,8 +17,8 @@ for binary in ./debug/*; do
 		test_file="$basename.test.c"
 		success=true
 
-		echo "===> $basename"
-		if [ "$1" == "--quick" ]; then
+		echo -e "${color_blue}===> $basename${color_reset}"
+		if [ "$1" == "--quick" ] || grep -q "@disable-valgrind" "$test_file"; then
 			$binary || success=false
 		else
 			valgrind --quiet --error-exitcode=42 $binary || success=false
@@ -25,10 +26,10 @@ for binary in ./debug/*; do
 
 		must_exist=$(cat "$test_file" | \
 					grep -E '^TEST\(\s*([a-z_]+).*$' | \
-					sed -E 's/^TEST\([[:space:]]*([a-z_]+).*$/RUN[0-9]*(\1/g')
-		for regex in $must_exist; do
-			if  ! grep -q $regex "$test_file"; then
-				echo -e "${color_red}RUN missing: $regex${color_reset}"
+					sed -E 's/^TEST\([[:space:]]*([a-z_]+).*$/\1/g')
+		for func in $must_exist; do
+			if  ! grep -q "RUN[0-9]*($func" "$test_file"; then
+				echo -e "${color_red}RUN missing: $func${color_reset}"
 				success=false
 			fi
 		done
