test: if all tests are being run

diff --git a/test b/test
--- a/test
+++ b/test
@@ -4,23 +4,44 @@ norm() {
 	fd '^(libft.h|ft_[^\.]+\.c)$' -X norminette
 }
 
+color_red="\033[0;31m"
+color_reset="\033[0m"
+
 failed=""
 
 make test || exit 1
 for binary in ./debug/*; do
 	if [ -f $binary ]; then
-		echo "===> $(basename $binary)"
-		$binary || failed="$failed$(basename $binary) "
+		basename="$(basename $binary)"
+		test_file="$basename.test.c"
+		success=true
+
+		echo "===> $basename"
+		$binary || success=false
+
+		must_exist=$(cat "$test_file" | \
+					grep -E '^TEST\(\s*([a-z_]+).*$' | \
+					sed -E 's/^TEST\([[:space:]]*([a-z_]+).*$/RUN\(\1/g')
+		for regex in $must_exist; do
+			if  ! grep -q $regex "$test_file" && \
+				! grep -q '@test ignore_run_check' "$test_file"; then
+				echo -e "${color_red}RUN missing: $regex${color_reset}"
+				success=false
+			fi
+		done
+		if [ $success == false ]; then
+			failed="$failed$(basename $binary) "
+		fi
 	fi
 done
 
 if [ -n "$failed" ]; then
 	echo >&2
-	echo -e "\033[0;31mfailed tests: $failed\033[0m" >&2
+	echo -e "${color_red}failed tests: $failed${color_reset}" >&2
 fi
 
-if norm | grep -E '^(Error|Warning)' 2>&1 >/dev/null; then
+if norm | grep -q -E '^(Error|Warning)'; then
 	echo >&2
-	echo -e "\033[0;31mnorm failed:\033[0m" >&2
+	echo -e "${color_red}norm failed:${color_reset}" >&2
 	norm
 fi
